export const paths = {
  LANDING_PAGE: "/",
  LOGIN_PAGE: "/login",
  REGISTER_PAGE: "/register",
  VILLAGE_PAGE: "/village",
  VILLAGE_PROFILE_PAGE: "/village/profile",
  DETAIL_VILLAGE_PAGE: "/village/detail/:id",
  INNOVATOR_PAGE: "/innovator",
  INNOVATOR_DETAIL: "/innovator/detail",
  INNOVATOR_PROFILE_PAGE: "/innovator/profile",
  DETAIL_INNOVATOR_PAGE: "/innovator/detail/:id",
  INNOVATION_PAGE: "/innovation",
  ADD_INNOVATION: "/innovation/add",
  INNOVATION_CATEGORY_PAGE: "/innovation/:category",
  DETAIL_INNOVATION_PAGE: "/innovation/detail/:id",
  DETAIL_INNOVATION: "/innovation/detail",
  EDIT_INNOVATION_PAGE: "/innovation/edit/:id",

  NOTIFICATION_PAGE : "/notification",
  RESET_PASSWORD_PAGE: "/resetpassword",
  EMAIL_RESET_PASSWORD_PAGE: "/emailreset",
  NEW_PASSWORD_PAGE: "/resetpassword/newpassword", 
  ADMIN_PAGE: "/admin",
  VERIFICATION_PAGE:"/admin/verification/:category",
  MAKE_ADS: "/admin/ads/make",
};
